// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByd1GeXCuyoqqWyBIaHw1MwVItG8cAeaU',
    appId: '1:667915199060:web:586fbd51f9b495dd9ec3c1',
    messagingSenderId: '667915199060',
    projectId: 'fir-message-b2d39',
    authDomain: 'fir-message-b2d39.firebaseapp.com',
    storageBucket: 'fir-message-b2d39.firebasestorage.app',
    measurementId: 'G-Q5EL00J0MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB08uN43I2Mss2fp7S2E_uTyoj-QKOsPuU',
    appId: '1:667915199060:android:d5af7b369dced6b59ec3c1',
    messagingSenderId: '667915199060',
    projectId: 'fir-message-b2d39',
    storageBucket: 'fir-message-b2d39.firebasestorage.app',
  );
}
